### ISSUE TITLE
Quantization

### ISSUE THREAD

**Issue by nshusa** [nshusa/better-sprite-packer-gui#6]
Need a better way to convert a PNG to PNG-8 with a good lossless compression algorithm

**Comment by IanWONeill** [comment]
I found some information on Stack, ive been using online compression tools myself but you may be able to come up with something better.

"Have a look at the ImageWriterParam class in the same package as the ImageIO class. It mentions compression.

https://docs.oracle.com/javase/7/docs/api/javax/imageio/ImageWriteParam.html

Also look at the example at http://exampledepot.com/egs/javax.imageio/JpegWrite.html and see if it translates well for PNG files."

And also this git repo - https://github.com/depsypher/pngtastic/

See what you can do (:

**Comment by nshusa** [comment]
@IanWONeill I'll check it out, thanks.

**Comment by nshusa** [comment]
@IanWONeill I figured it out. Jagex actually stores all of their sprites as GIF's not PNG's like I was doing. Jagex sprites have very very similar design to GIF's.

**GIFs**
* Limited to 256 colors
* Uses a palette
* Compressed with lossless compression algorithm
* No trans (trans is set in the client)

**Comment by nshusa** [comment]
Transparency is an issue if I quantize the image. Not entirely sure what the issue is. I compared the difference between the original image and the modified image. The only difference I see is the modified is off 1 blue value from the original. I changed the modified but didn't seem to fix the issue.

**Comment by nshusa** [comment]
I'm going to close this once again since I'm going to let the user reduce the amount of colors. Photoshop and GIMP are far better than something that's open source I can implement into this project.
